// -----------------------------------------------------------------------------
// page-layout.typ
//
// Shared page layout utilities for Typst-based PDF documents in Quarto.
//
// This file defines a reusable page-layout() function that applies:
//
// - running headers
// - running footers
// - page numbering
// - optional logos
// - consistent spacing/alignment
//
// Intended for use across:
//
// - exams
// - worksheets
// - rubrics
// - instructor documents
// - LA documents
//
// This file should remain document-agnostic.
// Do not put exam-specific or course-specific formatting here.
// -----------------------------------------------------------------------------


// -----------------------------------------------------------------------------
// page-layout()
//
// Applies a consistent header/footer layout to a document body.
//
// In Quarto, this function is normally activated indirectly through
// page-layout-header.typ. A course repository should include both files in its
// Typst configuration:
//
// format:
//   typst:
//     template-partials:
//       - tlm-styles/typst/partials/page.typ
//     include-in-header:
//       - file: tlm-styles/typst/page-layout.typ
//       - file: tlm-styles/typst/page-layout-header.typ
//
// The QMD document then supplies the content used by the layout through
// metadata:
//
// short-title: "Midterm Exam"
// course-label: "STAT 201 Inference"
// document-context: "Bayes | Fa 2026"
// footer-logo: "path/to/logo.png"
//
// page-layout-header.typ maps these metadata values to the arguments of
// page-layout().
//
// Notes:
//
// - The short title is hidden on page 1 to reduce redundancy.
// - The footer logo is optional.
// - Image paths are resolved in the context of the rendered Quarto project.
// - Quarto's default brand-logo page background is disabled separately by
//   typst/partials/page.typ.
// -----------------------------------------------------------------------------

#let page-layout(
  body,

  // Short document title shown in the running header.
  // Example: "Midterm Exam"
  short-title: "",

  // Course label shown in the upper-right header.
  // Example: "STAT 201 Inference"
  course-label: "",

  // Document context shown in the lower-left footer.
  // Example: "Bayes | Fa 2026"
  document-context: "",

  // Optional logo image path.
  // Set to none to disable the logo.
  logo: none,

  // Header/footer typography settings.
  header-size: 8.5pt,
  footer-size: 8pt,

  // Width of the footer logo image.
  logo-width: 0.32in,
  
  
) = {

  // ---------------------------------------------------------------------------
  // Global page settings
  // ---------------------------------------------------------------------------

  set page(

    // Distance from the top edge of the page to the header.
    // Adjust if the header appears too close to the body content.
    header-ascent: 0.35in,
    footer-descent: 0.35in,

    // -------------------------------------------------------------------------
    // Running header
    // -------------------------------------------------------------------------

    header: context {

      set text(size: header-size)

      block(
        inset: (bottom: 3pt),

        [
          // Two-column header layout:
          //
          // left  = document title
          // right = course label
          #grid(
            columns: (1fr, 1fr),

            align(left)[

              // Hide the short document title on page 1.
              // This avoids repeating the title immediately below
              // the document title block generated by Quarto.
              #if counter(page).get().first() > 1 {
                short-title
              }
            ],

            align(right)[
              #course-label
            ],
          )
          
          #v(3pt)
          
          // Horizontal separator line below the header.
          #line(length: 100%, stroke: 0.4pt)
        ],
      )
    },


    // -------------------------------------------------------------------------
    // Running footer
    // -------------------------------------------------------------------------

    footer: context {

      set text(size: footer-size)

      block(
        inset: (top: 3pt),

        [
          // Horizontal separator line above the footer.
          #line(length: 100%, stroke: 0.4pt)
          #v(3pt)
          
          // Three-column footer layout:
          //
          // left   = instructor/semester label
          // center = page number
          // right  = optional logo
          #grid(
            columns: (1fr, auto, 1fr),

            align(left)[
              #document-context
            ],

            align(center)[
              #counter(page).display()
            ],

            align(right + horizon)[
            
              // Render the logo only if one is provided.
              // The box height roughly matches the footer text line height so the image
              // aligns visually with the footer text instead of sitting too low.
              #if logo != none {
                box(
                  height: logo-width,
                  baseline: 0pt,
                  move(
                    dy: -9pt,
                    image(logo, width: logo-width)
                  )
                )
              }
            ],
          )
        ],
      )
    },
  )

  // Render the document body after applying the page layout.
  body
}